# ./.github/workflows/staging-auto-pr.yaml
name: Staging Auto-PR
on:
  push:
    branches: ['dev', 'Dev-0.0.1', 'Dev-0.0.2', 'Dev-0.0.3', 'Dev-0.0.4', 'Dev-0.0.5', 'Dev-0.0.6', 'Dev-0.0.7', 'Dev-0.0.8', 'Dev-0.0.9', 
              'Dev-0.1.0', 'Dev-0.1.1', 'Dev-0.1.2', 'Dev-0.1.3', 'Dev-0.1.4', 'Dev-0.1.5', 'Dev-0.1.6', 'Dev-0.1.7', 'Dev-0.1.8', 'Dev-0.1.8', 'Dev-0.1.9']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "SmartGuyCodes"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}